# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.9.4
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.32.0

clusterName: tslamars-talos-cluster
endpoint: https://10.10.4.199:6443
clusterPodNets:
  - 10.14.0.0/16
clusterSvcNets:
  - 10.15.0.0/16
additionalApiServerCertSans:
  - 10.10.4.199
  - 127.0.0.1
additionalMachineCertSans:
  - 10.10.4.199
  - 127.0.0.1
nodes:
  - hostname: talos-master-00
    controlPlane: true
    ipAddress: 10.10.4.170
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "6a:a1:5e:45:67:6e"
        dhcp: false
        vip:
          ip: 10.10.4.199
  - hostname: talos-master-01
    controlPlane: true
    ipAddress: 10.10.4.171
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "6a:a1:5e:45:67:6e"
        dhcp: false
        vip:
          ip: 10.10.4.199
  - hostname: talos-master-02
    controlPlane: true
    ipAddress: 10.10.4.172
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "c6:76:c3:17:17:00"
        dhcp: false
        vip:
          ip: 10.10.4.199
  - hostname: talos-worker-00
    controlPlane: false
    ipAddress: 10.10.4.180
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "ca:f5:cb:81:c6:ab"
        dhcp: false
    patches:
      - |-
        machine:
          udev:
            rules:
              - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
              - SUBSYSTEM=="drm", KERNEL=="card*", GROUP="44", MODE="0660"

  - hostname: talos-worker-01
    controlPlane: false
    ipAddress: 10.10.4.181
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "76:33:d1:05:84:ac"
        dhcp: false
  - hostname: talos-worker-02
    controlPlane: false
    ipAddress: 10.10.4.182
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "da:d2:41:c1:6b:fe"
        dhcp: false

patches:

  # Force nameserver
  - |-
    machine:
      network:
        nameservers:
          - 1.1.1.1
          - 1.0.0.1

  # Configure NTP
  - |-
    machine:
      time:
        disabled: false
        servers: ["time.cloudflare.com"]

controlPlane:
  patches:
    # Cluster configuration
    - |-
      cluster:
        # allowSchedulingOnControlPlanes: true
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        proxy:
          disabled: true
        network:
          cni:
            name: none
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
worker:
  patches:
    # Machine configuration
    - |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/mnt/longhorn
              type: bind
              source: /var/mnt/longhorn
              options:
                - bind
                - rshared
                - rw
        disks:
            - device: /dev/sdb
              partitions:
                - mountpoint: /var/mnt/longhorn