# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.9.4
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.31.0

clusterName: tslamars-talos-cluster
endpoint: https://10.10.5.199:6443
clusterPodNets:
  - 10.14.0.0/16
clusterSvcNets:
  - 10.15.0.0/16
additionalApiServerCertSans:
  - 10.10.5.199
  - 127.0.0.1
additionalMachineCertSans:
  - 10.10.5.199
  - 127.0.0.1
nodes:
  - hostname: talos-marsmaster-00
    controlPlane: true
    ipAddress: 10.10.5.170
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e6:04:7c:d2:d9:58"
        dhcp: false
        vip:
          ip: 10.10.5.199
  - hostname: talos-marsmaster-01
    controlPlane: true
    ipAddress: 10.10.5.171
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "ea:52:ce:62:1b:f6"
        dhcp: false
        vip:
          ip: 10.10.5.199
  - hostname: talos-marsmaster-02
    controlPlane: true
    ipAddress: 10.10.5.172
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "76:81:1e:b1:10:18"
        dhcp: false
        vip:
          ip: 10.10.5.199
  - hostname: talos-marsworker-00
    controlPlane: false
    ipAddress: 10.10.5.180
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "0e:16:b5:49:7c:91"
        dhcp: false
    patches:
      - |-
        machine:
          udev:
            rules:
              - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
              - SUBSYSTEM=="drm", KERNEL=="card*", GROUP="44", MODE="0660"

  - hostname: talos-marsworker-01
    controlPlane: false
    ipAddress: 10.10.5.181
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "f6:7f:d4:18:32:e4"
        dhcp: false
  - hostname: talos-marsworker-02
    controlPlane: false
    ipAddress: 10.10.5.182
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "9a:be:68:9c:fa:56"
        dhcp: false

patches:

  # Force nameserver
  - |-
    machine:
      network:
        nameservers:
          - 1.1.1.1
          - 1.0.0.1

  # Configure NTP
  - |-
    machine:
      time:
        disabled: false
        servers: ["time.cloudflare.com"]

controlPlane:
  patches:
    # Cluster configuration
    - |-
      cluster:
        # allowSchedulingOnControlPlanes: true
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        proxy:
          disabled: true
        network:
          cni:
            name: none
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
worker:
  patches:
    # Machine configuration
    - |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/mnt/longhorn
              type: bind
              source: /var/mnt/longhorn
              options:
                - bind
                - rshared
                - rw
        disks:
            - device: /dev/sdb
              partitions:
                - mountpoint: /var/mnt/longhorn